export const ROUTES = {
  SWAP: "/swap",
  MARKET: "/market",
  PORTAl: "/portal",
  PROFILE: "/profile",
  GAME: "/games",
  GAME_DETAIL: "/games/:id",
  LEADER_BOARD: "/leaderboard",
  MINT: "/mint",
  FUTURES: "/futures",
  REFERRAL: "/referral",
  SCAN_QR: "/scan-qr",
  INVOICE: "/invoice/:id",
  PAYMENT_METHOD: "/payment-method",
  HISTORY: "/history",
  HISTORY_DETAIL: "/history/:id",
  EXPLORE: "/explore",
  EXPLORE_DETAIL: "/explore/:id",
  INVITE: "/invite",
  SPIN: "/spin",
  SPIN_REWARDS: "/spin/rewards",
  DASHBOARD: '/',
  VERSION: "/version",
};
